name: CI Java

on:
  push:
    branches:
      - main
      - 'G*'

# Define um conjunto de steps que pode ser reutilizado
jobs:
  comum:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar repositório
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

  construir:
    needs: comum
    runs-on: ubuntu-latest

    steps:
      - name: Verificar dependências
        run: mvn dependency:resolve

      - name: Construir com Maven
        run: mvn -B clean install

  testar:
    needs: comum
    runs-on: ubuntu-latest

    steps:
      - name: Executar testes
        run: mvn test
