name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Verify dependencies and package
        run: mvn package

      - name: Login to Docker Hub
        run: echo "#Galasdalas50" | docker login -u "gacacio" --password-stdin

      - name: Build imagem docker
        run: |
          docker build . --file Dockerfile --tag gerenciador:latest

      - name: Deploy image
        run: |
          docker tag gerenciador:latest gacacio/gerenciador:latest
          docker push gacacio/gerenciador:latest