name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Verify dependencies and package
        run: mvn package

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build imagem docker
        run: |
          docker build . --file Dockerfile --tag gerenciador:$(date +%s)

      - name: Deploy image
        run: |
          docker tag gerenciador:$(date +%s) gacacio/gerenciador:$(date +%s)
          docker push gacacio/gerenciador:$(date +%s)