name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar repositório
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Verificar dependências
        run: mvn dependency:resolve

      - name: Construir com Maven
        run: mvn -B clean install

  testar:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Verificar repositório
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Executar testes
        run: mvn test

  deploy-imagem:
    runs-on: ubuntu-latest

    needs: testar

    steps:
      - name: Verificar repositório
        uses: actions/checkout@v2

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Verificar dependências e package
        run: mvn package

      - name: Login to Docker Hub
        run: echo "#Galasdalas50" | docker login -u "gacacio" --password-stdin

      - name: extrair versão do pom
        run: echo "::set-env name=PROJECT_VERSION::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

      - name: Build imagem docker
        run: |
          docker build . --file Dockerfile --tag gerenciador:${{ env.PROJECT_VERSION }}

      - name: Deploy image
        run: |
          docker tag gerenciador:${{ env.PROJECT_VERSION }} gacacio/gerenciador:${{ env.PROJECT_VERSION }}
          docker push gacacio/gerenciador:${{ env.PROJECT_VERSION }}