name: Atualizar Versão Após Merge na Main

on:
  push:
    branches:
      - main

jobs:
  atualizar-versao:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar código
        uses: actions/checkout@v2

      - name: Configurar Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Atualizar Versão
        run: |
          # Atualize o número da versão no arquivo pom.xml
          nova_versao=$(awk -F '[<>]' '/<version>/{print $3}' pom.xml | awk -F. '{$NF++; OFS="."; print $0}')
          sed -i "s|<version>.*</version>|<version>${nova_versao}</version>|" pom.xml

      - name: Commit e Push das mudanças
        run: |
          git config --local user.email "action@github.com"
          git config -l
          git commit -am "Auto-atualização da versão para $nova_versao [skip ci]"
          git push

      - name: Criar Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Auto-atualização da versão para $nova_versao"
          labels: "auto-atualizacao"
